apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-tesseris-chat
  namespace: default
  labels:
    app: erp-tesseris-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-tesseris-chat
  template:
    metadata:
      labels:
        app: erp-tesseris-chat
    spec:
      containers:
        - name: erp-tesseris-chat
          image: __DOCKER_IMAGE__:__TAG__
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: NODE_ENV
              value: "production"
            - name: SPRINGBOOT_SERVICE_URL
              value: "http://springboot-service:19091"
            - name: REACT_FRONTEND_URL
              value: "http://localhost:4173"
            - name: REACT_ADMIN_URL
              value: "http://localhost:7001"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /status
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL 